<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Minhas Séries</title>
</head>
<body>

    <div id="conteiner">
        <header>
            <h1>Minhas Séries</h1>
        </header>
        <nav>
            <ul>
                <li><a href="index.php">Início</a></li>
                <li><a href="#">Cadastros</a>
                    <ul>
                        <li><a href="Request.php?class=GeneroCtr&method=exibirView">Genero</a></li>
                        <li><a href="#">Series</a></li>
                    </ul>
                </li>

            </ul>
        </nav>

        <div id="conteudo">
        
        