<h2>Cadastro de Gênero</h2>
<hr>
<form action="#" method="post">

<input type="hidden" name="id" id="id" 
     value="<?= $this->model->getId() ?>">

<label for="nome">Nome do Gênero</label><br>

<input type="text" name="nome" id="nome" 
     value="<?= $this->model->getNome() ?>"><br>

<input type="submit" name="comando" value="Limpar">
<input type="submit" name="comando" value="Salvar">
<input type="submit" name="comando" value="Excluir">


</form>